custom2fa/urls.py
# django
from django.conf.urls import url
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required
from django.views.defaults import permission_denied
# apps
from apps.otp import forms, views
from apps.otp.decorators import otp_required

urlpatterns = [
    # admin
    url(
        r'^admin/',
        admin.site.urls
    ),
    # login
    path(
        'login/',
        views.OTPLoginView.as_view(),
        name="login"
    ),
    # logout
    path(
        'logout/',
        views.OTPLogoutView.as_view(),
        name="logout"
    ),
    # front
    path(
        '',
        TemplateView.as_view(
            template_name='pages/front.html'
        ),
        name='front'
    ),
    # profile
    path(
        'profile/',
        otp_required( views.OTPProfile.as_view() ),
        name='profile'
    ),
    # token form
    path('verify/',
        views.TokenFormView.as_view(),
        name='token_form'
    ),
    # private
    path(
        'private/',
        otp_required( TemplateView.as_view(
            template_name='pages/private.html'
        )),
        name="private"
    ),
]

apps/otp/models.py
# python
import os
import binascii
import time
from base64 import b32encode
from binascii import unhexlify
# django
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.encoding import force_str
from django.core.mail import send_mail
# project
from .utils import totp

def random_hex(length=20):
    """
    Returns a string of random bytes encoded as hex.

    This uses :func:`os.urandom`, so it should be suitable for generating
    cryptographic keys.

    :param int length: The number of (decoded) bytes to return.

    :returns: A string of hex digits.
    :rtype: str

    """
    return os.urandom(length).hex()

def random_hex_str(length=20):
    # Could be removed once we depend on django_otp > 0.7.5
    return force_str(random_hex(length=length))

class OTPUser(AbstractUser):

    device = models.CharField(
        'Device',
        max_length=1,
        choices=(
            ('0', 'No usar 2FA'),
            ('1', 'Correo electrónico'),
            ('2', 'App de autenticación')
        ),
        default='0'

    )
    key = models.CharField(
        max_length=40,
        default=random_hex_str,
        help_text="Hex-encoded secret key"
    )
    last_token_time = models.BigIntegerField(
        default = -1,
    )

    def verify_token(self, other):
        key = binascii.unhexlify(self.key.encode())
        token = totp(key)
        t = time.time()
        if t > self.last_token_time and token == other:
            self.last_token_time = t
            self.save(update_fields=['last_token_time'])
            return True
        return False

    @property
    def b32_key(self):
        rawkey = unhexlify(self.key.encode('ascii'))
        return b32encode(rawkey).decode('utf-8')

    @property
    def has_2fa_enabled(self):
        return self.device != '0'

    def send_token_email(self):
        key   = binascii.unhexlify(self.key.encode())
        token = totp(key)
        print(token)
        send_mail(
            subject="Your OTP Password",
            message="Your OTP password is %s" % token,
            from_email='no-reply@maadix.net',
            recipient_list=[self.email]
        )

    def __str__(self):
        return self.username

templates/base.html
<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8" />
        <title>
            Custom 2FA
        </title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style>
            body { padding: 24px; font-family: monospace }
            .login-info { position: fixed; top: 12px; right: 12px; padding: 12px; text-align: right; background: #eee}
            .login-info a { margin: 0 12px; }
        </style>
        {% block extra_media %}
            {# Override this in templates to add extra stylesheets and js #}
        {% endblock %}
    </head>

    <body class="{% block body_css_classes %}{% endblock %} {% if not request.user.is_anonymous %}logged-in{% endif %}">

        <div class="login-info">
            {% if request.user.is_authenticated %}
            <p>User logged-in as <strong>{{ request.user.username }}</strong></p>
            {% if request.user.is_verified == True %}
                <p style="color: green">User verified
            {% elif request.user.has_2fa_enabled %}
                <p style="color: red">User not verified
            {% endif %}
            ({{ request.user.get_device_display }})</p>
            <a href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a href="{% url 'login' %}">Login</a>
            {% endif %}
            <a href="{% url 'profile' %}">Profile url</a>
            <a href="{% url 'private' %}">Private url</a>
        </div>
        {# Site messages #}
        {# include 'components/messages.html' #}

        {# content #}
        <main class="region-content">
            {% block page %}{% endblock %}
        </main>

        {% block extra_js %}
            {# Override this in templates to add extra javascript #}
        {% endblock %}
    </body>
</html>